services:
    _defaults:
        public: true

    YsTools\Bundle\OroCommerceElfsightBundle\Controller\ElfsightWidgetController:
        arguments:
            - '@oro_config.organization'
            - '@oro_security.token_accessor'
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
