services:
    _defaults:
        public: true

    YsTools\Bundle\OroCommerceElfsightBundle\Controller\ElfsightWidgetController:
        arguments:
            - '@security.token_storage'
            - '@oro_config.user'
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
