datagrids:
    ystools-elfsight-widget-grid:
        extended_entity_name: YsTools\Bundle\OroCommerceElfsightBundle\Entity\ElfsightWidget
        acl_resource: elfsight_widget_view
        source:
            type: orm
            query:
                select:
                    - widget.id
                    - widget.identifier
                    - widget.name
                    - widget.createdAt
                    - widget.updatedAt
                from:
                    - { table: YsToolsOroCommerceElfsightBundle:ElfsightWidget, alias: widget }
        inline_editing:
            enable: true
        columns:
            name:
                label: ystools.orocommerceelfsight.elfsightwidget.name.label
                inline_editing:
                    enable: true
            identifier:
                label: ystools.orocommerceelfsight.elfsightwidget.identifier.label
                inline_editing:
                    enable: false
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
            actions:
                type: twig
                label: ''
                frontend_type: html
                template: '@YsToolsOroCommerceElfsight/ElfsightWidget/Datagrid/actionsColumn.html.twig'
                align: right
        properties:
            id: ~
        sorters:
            columns:
                name:
                    data_name: widget.name
                identifier:
                    data_name: widget.identifier
                createdAt:
                    data_name: widget.createdAt
                updatedAt:
                    data_name: widget.updatedAt
            default:
                createdAt: DESC
        filters:
            columns:
                name:
                    type: string
                    data_name: widget.name
                identifier:
                    type: string
                    data_name: widget.identifier
                createdAt:
                    type: datetime
                    data_name: widget.createdAt
                updatedAt:
                    type: datetime
                    data_name: widget.updatedAt
