dynamic-imports:
    ystools_orocommerce_elfsight:
        - ystoolsorocommerceelfsight/js/components/elfsight-identifier-form-component
        - ystoolsorocommerceelfsight/js/components/edit-elfsight-widget-component
