navigation:
    menu_config:
        items:
            elfsight_widgets_list:
                label:           'ystools.orocommerceelfsight.elfsightwidget.entity_plural_label'
                route:           'ystools_orocommerce_elfsight_index'
                position:        1000
        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                            elfsight_widgets_list: ~
