placeholders:
    placeholders:
        scripts_after:
            items:
                elfsight_embed_sdk:
                    order: 200
        index_navButtons_before:
            items:
                elfsight_redirect_button:
                    order: 100
    items:
        elfsight_embed_sdk:
            template: 'YsToolsOroCommerceElfsightBundle:ElfsightWidget:embed_sdk.html.twig'
        elfsight_redirect_button:
            template: 'YsToolsOroCommerceElfsightBundle:ElfsightWidget:redirect_button.html.twig'
            applicable: '@oro_ui.placeholder.filter->isSame($entity_class$, Oro\Bundle\CMSBundle\Entity\ContentWidget)'
